FROM node:16.13.1-alpine AS build

ARG USER=node

WORKDIR /app

COPY --chown=node:node package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY --chown=node:node . /app

RUN yarn build

USER $USER

FROM node:18-alpine 

RUN mkdir ./dist && mkdir ./node_modules

COPY --chown=node:node --from=build /app/node_modules ./node_modules
COPY --chown=node:node --from=build /app/dist ./dist

EXPOSE 3000

CMD [ "node", "/dist/main" ]
