FROM node:16.13.1-alpine AS build

ARG USER=node

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . /app

RUN yarn build:prod

FROM nginx:1.20.2-alpine

COPY --from=build /app/dist/cqi-2023 /usr/share/nginx/html

EXPOSE 80

USER $USER
